name: test

on:
  pull_request:

jobs:
  init:
    runs-on: ubuntu-latest
    if: github.repository == 'aerokube/init'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ~1.24.0

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: ci/test.sh

      - name: Build
        run: ci/build.sh
